### ISSUE TITLE
Some languages have wrong number of lexemes

### ISSUE THREAD

**Issue by Vesihiisi** [Vesihiisi/Wikidata-Senses#6]
There's a mismatch in how the number of sense-less lexemes is determined, most probably because of a fucked up useless query somewhere.

let's look at Sranan Tongo (srn)

[This query](https://query.wikidata.org/#%23Lemmas%20with%20no%20senses%0ASELECT%20%3Fl%20%3Flemma%20WHERE%20%7B%0A%20%20%20%3Fl%20a%20ontolex%3ALexicalEntry%20%3B%20dct%3Alanguage%20%3Flanguage%20%3B%0A%20%20%20%20%20%20%20%20wikibase%3Alemma%20%3Flemma%20.%0A%20%20%3Flanguage%20wdt%3AP218%20%27srn%27%0A%20%20FILTER%20NOT%20EXISTS%20%7B%3Fl%20ontolex%3Asense%20%3Fsense%20%7D%0A%7D%0AORDER%20BY%20%3Flemma) is used to find the Sranan Tongo items that lack senses with glosses in Sranan Tongo. The result is 0. A manual review shows this is wrong, as I can find https://www.wikidata.org/w/index.php?title=Lexeme:L456&oldid=683918437 and others.

[This query](https://query.wikidata.org/#SELECT%20%3Fnumber_of_lexemes%20%3Flanguage%20%3FlanguageLabel%20%3FlanguageCode%0A%20%20%20%20WITH%20%7BSELECT%20%3Flanguage%20%28COUNT%28%3Fl%29%20AS%20%3Fnumber_of_lexemes%29%20WHERE%20%7B%0A%20%20%20%20%3Fl%20a%20ontolex%3ALexicalEntry%20%3B%0A%20%20%20%20dct%3Alanguage%20%3Flanguage%20%3B%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%3Fl%20ontolex%3Asense%20%3Fsense%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Flanguage%20%7D%0A%20%20%20%20AS%20%25languages%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20INCLUDE%20%25languages%0A%20%20%20%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%20%20%20%20%20%20%3Flanguage%20wdt%3AP424%20%3FlanguageCode.%0A%20%20%20%20%7D%0A%20%20%20%20ORDER%20BY%20DESC%28%3Fnumber_of_lexemes%29%0A%20%20%20%20LIMIT%2050) populates the front page. It says there's 20 such items for Sranan Tongo, which seems correct. But if you click on it, there's an error because the 1st query doesn't find any items.

**Comment by lucaswerkmeister** [comment]
You’re using different language code properties: [Wikimedia language code (P424)](https://www.wikidata.org/wiki/Property:P424) for the index page, but [ISO 639-1 code (P218)](https://www.wikidata.org/wiki/Property:P218) for an individual language. And `srn` is not a two-letter code, so [Sranan Tongo (Q33989)](https://www.wikidata.org/wiki/Q33989) has statements for [ISO 639-2 code (P219)](https://www.wikidata.org/wiki/Property:P219) and [ISO 639-3 code (P220)](https://www.wikidata.org/wiki/Property:P220), but not for [ISO 639-1 code (P218)](https://www.wikidata.org/wiki/Property:P218).
